### ISSUE TITLE
incompatible with React version below 0.13.0

### ISSUE THREAD

**Issue by raorao** [Hacker0x01/react-datepicker#134]
attempting to load, I get the following error:

```
Uncaught TypeError: React.findDOMNode is not a function
```

The `findDOMNode` API was introduced in [React 0.13](https://github.com/facebook/react/blob/master/CHANGELOG.md#0130-march-10-2015), which is the root cause of the problem. I'd be happy to put in a fix, although perhaps the library is meant not to support older versions of React. interested to hear your thoughts.

**Comment by martijnrusschen** [comment]
Hi @raorao. This is something that was added in React 0.13. We're happy to support merge a PR that adds backward compatibility of the React 0.12 behaviour, but be aware that React is still in beta and you will continue having breaking changes until React hits 1.0.

**Comment by bmcneely** [comment]
As a related question, is there anything in React 0.14 that breaks this component? Just looking at what versions of React it allows in the package.json and wondering why. Regardless, it probably shouldn't allow versions below 0.13 if the error that @raorao mentioned is occurring on those versions.

**Comment by martijnrusschen** [comment]
I haven't tried it yet, but I'm happy to merge a PR that ups the React version :)

**Comment by martijnrusschen** [comment]
This works with 0.14 now.
